import { createContext, useContext, useState } from "react";

const strings = {
  nl: {
    brandSub: "Video Production Studio",
    navStudio: "Studio",
    navBeheer: "Beheer",
    navEditors: "Editors",
    team: "Team",
    logout: "Uitloggen",
    logoutConfirmTitle: "Uitloggen?",
    logoutConfirmBody: "Weet je zeker dat je wilt uitloggen?",
    home: "Home",
    agenda: "Agenda",
    klanten: "Klanten",
    taken: "Taken",
    archief: "Archief",
    workspace: "Workspace",
    checker: "Video Checker",
    pulse: "Studio Pulse",
    activeClients: "Actieve klanten",
    openTasks: "Open taken",
    shootsMonth: "Shoots deze maand",
    urgent: "Urgent",
    kpiTasksInProgress: "Taken in uitvoering",
    kpiUrgentClients: "Urgente klanten",
    kpiDescOngoingProjects: "Lopende trajecten",
    kpiDescScheduled: "Gepland in agenda",
    kpiDescAcrossProjects: "Over alle projecten",
    kpiDescRequiresAttention: "Vereist aandacht",
    dayModalNoEvents: "Geen events op deze dag.",
    addEventToDay: "+ Event toevoegen",
    eventFormTitle: "Nieuw event toevoegen",
    eventFormTitleEdit: "Event bewerken",
    eventDateTimeLabel: "Datum en tijd",
    eventAssigneeLabel: "Toegewezen aan",
    eventAssigneePlaceholder: "— Kies teamlid —",
    eventNameLabel: "Naam",
    eventNamePlaceholder: "Event naam…",
    eventDateLabel: "Datum",
    eventClientLabel: "Klant",
    eventClientPlaceholder: "— Kies klant —",
    eventNotesPlaceholder: "Optioneel…",
    thisWeek: "Deze week",
    nextWeek: "Volgende week",
    homeStudioSubtitle: "Studio overzicht · 4REEL Productions",
    activity: "Activiteit",
    clientActivityOverview: "Client activiteit overzicht",
    clientActivityEmpty: "Nog geen client activiteit",
    clientActivityLoadError: "Client activiteit kon niet worden geladen",
    portalUnknownClient: "Onbekende klant",
    portalClientEventFallback: "Nieuwe portal activiteit",
    portalDateUnknown: "Onbekende datum",
    contact: "Contactpersoon",
    phone: "Telefoon",
    clientSince: "Klant sinds",
    phase: "Fase",
    statusLabel: "Status",
    urgentStatus: "Urgent",
    active: "Actief",
    notes: "Notities",
    todo: "Te doen",
    bezig: "Bezig",
    review: "Review",
    klaar: "Klaar",
    filter: "Filter:",
    allTasks: "Alle",
    tasksKanbanSubtitle: "Projecttaken over alle klanten",
    addTask: "+ Taak",
    addEvent: "+ Nieuw event",
    save: "Opslaan",
    cancel: "Annuleren",
    close: "Sluiten",
    delete: "Verwijderen",
    restore: "↩ Herstellen",
    archive: "→ Archiveren",
    wsFilmsLabel: "Filmpjes",
    wsFilmsReady: "klaar",
    wsVidColName: "Bestandsnaam",
    wsVidColFase: "Edit Fase",
    wsVidColAssets: "Assets Drive",
    wsVidColExport: "Export Frame.io",
    wsVidColNotes: "Notities",
    wsAddDrivePH: "+ Drive link toevoegen",
    wsAddExportPH: "+ Frame.io link",
    wsVidNamePrompt: "Naam van het filmpje:",
    wsAddWorkspace: "+ Workspace toevoegen",
    wsAddNewBatch: "+ Nieuwe batch",
    wsAddWorkspaceFooter: "+ Workspace aanmaken",
    wsAddVideo: "+ Filmpje",
    wsBackAllBatches: "← Alle workspaces",
    wsDeleteWorkspace: "Workspace verwijderen",
    wsEditProject: "Project bewerken",
    wsConfirmDeleteBatch: "\"{name}\" verwijderen?",
    wsBackAllWorkspaces: "← Alle workspaces",
    wsBatchesLabel: "Batches",
    wsBatchesEmpty: "Nog geen batch. Maak er een aan om filmpjes toe te voegen.",
    wsNewBatchTitle: "Nieuwe batch",
    wsBatchNameLabel: "Batch naam",
    wsBatchNameExample: "Bijv. Shoot week 1",
    wsCreateBatch: "Batch aanmaken",
    wsDeleteBatchBtn: "Batch verwijderen",
    wsConfirmDeleteBatchSub: "Batch \"{name}\" en al zijn filmpjes verwijderen?",
    wsSelectBatchFirst: "Selecteer eerst een batch.",
    wsVideosInBatchNamed: "Filmpjes in {name} ({total})",
    wsShootLabel: "Shoot",
    wsShootStatusLabel: "Shoot status",
    wsShootDateLabel: "Shoot datum",
    wsShootTimeLabel: "Shoot tijd",
    wsShootTimeRequiredError: "Shoot tijd is verplicht.",
    wsDeadlineLabel: "Deadline",
    wsEditorLabel: "Editor",
    wsLeadEditorLabel: "Lead editor",
    wsTeamPlaceholder: "— Kies team —",
    wsProjectStageLabel: "Project fase",
    wsBatchNotes: "Batch notities",
    wsProjectLinksTitle: "🔗 Project links (Drive · LUTs · B-Roll · Premiere)",
    wsOpenLink: "Openen ↗",
    wsLinkLabelPlaceholder: "Label (bijv. LUTs folder)",
    wsLinkUrlPlaceholder: "https://drive.google.com/...",
    wsAddLink: "+ Link toevoegen",
    wsWorkflowTitle: "📋 Workflow — hoe werken we met deze bestanden?",
    wsWorkflowStep1Title: "Assets downloaden",
    wsWorkflowStep1Desc:
      "Download de footage via de Drive-link hierboven. Sla elke batch op in een aparte map op je lokale schijf. Hernoem de bestanden NIET.",
    wsWorkflowStep2Title: "Project aanmaken in Premiere",
    wsWorkflowStep2Desc:
      "Gebruik de Premiere Pro template via de link hierboven. Laad de LUTs-map in voor het correcte kleurprofiel per project.",
    wsWorkflowStep3Title: "Edit uitvoeren → status op \"In Progress\"",
    wsWorkflowStep3Desc:
      "Monteer de video op basis van de shotlist en interviewvragen. Zet de Edit Fase van jouw filmpje op In Progress zodra je begint.",
    wsWorkflowStep4Title: "Exporteren met exacte bestandsnaam",
    wsWorkflowStep4Desc:
      "Exporteer met de exacte naam zoals in de tabel hieronder, inclusief versienummer.",
    wsWorkflowStep5Title: "Upload naar Frame.io → link in Export kolom",
    wsWorkflowStep5Desc:
      "Upload het geëxporteerde filmpje naar Frame.io en plak de link in Export Frame.io.",
    wsWorkflowStep6Title: "Edit Fase → \"Waiting for Review\"",
    wsWorkflowStep6Desc:
      "Zet de Edit Fase op Waiting for Review. Na goedkeuring → Finished.",
    wsVideosInBatch: "Filmpjes in batch ({total})",
    wsVideosDoneProgress: "{done}/{total} klaar",
    wsFilenamePlaceholder: "Bestandsnaam…",
    wsEditScript: "Script bewerken",
    wsScriptAdd: "Script toevoegen…",
    wsDriveLinkPlaceholder: "Drive link…",
    wsOpenShotlist: "Shotlist openen",
    wsCreateShotlist: "Shotlist aanmaken…",
    wsEditSop: "SOP bewerken",
    wsFillSop: "SOP invullen…",
    wsNotePlaceholder: "Notitie…",
    wsInternApprovedSend: "Intern goedgekeurd — stuur naar klant",
    wsApproveInternFirst: "Eerst intern goedkeuren",
    wsToPortal: "→ Portaal",
    wsDeleteVideoAria: "Video verwijderen",
    wsConfirmDeleteVideo: "Video verwijderen?",
    wsOptionalNote: "Notitie (optioneel)",
    wsAddItem: "+ Toevoegen",
    wsNewVideoTitle: "Nieuw filmpje",
    wsVideoNameExample: "Bijv. Kalea_Intro_Reel_v1",
    wsPageSubtitle: "Project batches filmpjes statussen resources",
    wsShootDateHeader: "Shoot datum",
    wsShootStatusHeader: "Shoot status",
    wsBatchProjectHeader: "Batch / Project",
    wsVideosHeader: "Filmpjes",
    wsDeadlineHeader: "Deadline",
    wsStageHeader: "Fase",
    wsEditorHeader: "Editor",
    wsClientHeader: "Klant",
    wsFilmSingular: "film",
    wsFilmPlural: "films",
    wsNewWorkspaceProject: "Nieuw workspace project",
    wsProjectNameLabel: "Project naam",
    wsProjectNameExample: "bijv. Vermado Automotive S2",
    wsProjectNameRequired: "Project naam is verplicht.",
    wsEditorRoleEditor: "Editor",
    wsCreateProject: "Project aanmaken",
    wsScriptPlaceholder:
      "Plak of typ hier het script, de briefing of aandachtspunten voor deze video.\n\nTip: kopieer direct vanuit Google Docs of Notion.",
    wsScriptStats: "{words} woorden · {chars} tekens",
    wsCloseShootMode: "✕ Sluit shoot-modus",
    wsShotsDone: "shots geschoten",
    wsNoShots: "Nog geen shots. Voeg hieronder toe.",
    wsShotAddPlaceholder: "Shot toevoegen, bijv: Wide shot ingang · Close-up product…",
    wsScriptUnavailable:
      "Geen script beschikbaar voor deze video.\n\nVoeg een script toe via de Script kolom in de tabel.",
    wsSopFormatRatio: "🎞 Formaat & Ratio",
    wsSopDurationLabel: "Duur (bijv. 60s, 3 min YouTube)",
    wsSopDurationPlaceholder: "bijv. 60s reels + 3 min YouTube",
    wsSopStyleFeel: "🎨 Stijl & Gevoel",
    wsSopLutLabel: "Kleurprofiel / LUT",
    wsSopLutPlaceholder: "bijv. Warm, contrastrijk — LUT: Moody_v3",
    wsSopMusicAudio: "🎵 Muziek & Audio",
    wsSopMusicPlaceholder:
      "bijv. Energiek, upbeat. Geen tekst. Artlist — zoek op: urban cinematic",
    wsSopEditorInstructions: "📋 Instructies voor editor",
    wsSopInstructionsPlaceholder:
      "Bijv:\n• Begin met de sterkste shot\n• Jump cuts voor energie\n• Ondertitels verplicht op reels\n• Exporteer H.264, max 100MB\n• Kleur: warm en zonnig",
    wsSopTip:
      "💡 Vul dit in voor de editfase — dan weet de editor precies wat het doel is en zijn er minder revisions.",
    wsSopAutoSaved: "Automatisch opgeslagen · Klik buiten de modal om te sluiten",
    wsFase_tentative: "Tentative",
    wsFase_spotting: "Spotting Footage",
    wsFase_inprogress: "In Progress",
    wsFase_ready: "Ready to Edit",
    wsFase_intern_review: "Intern Review",
    wsFase_intern_approved: "Intern Goedgekeurd ✓",
    wsFase_waitreview: "Stuur naar klant →",
    wsFase_client_review: "In review bij klant",
    wsFase_client_revision: "Revisie aangevraagd",
    wsFase_client_approved: "Goedgekeurd door klant ✓",
    wsFase_uploaddrive: "Upload to Drive",
    wsFase_finished: "Finished ✓",
    wsGroup_intern: "── Intern ──",
    wsGroup_client: "── Klant ──",
    wsGroup_done: "── Afronden ──",
    wsTab_inbox: "Project Inbox",
    wsTab_stage: "Project Fase",
    wsTab_deadlines: "Post Deadlines",
    wsTab_shoots: "Geplande Shoots",
    wsTab_month: "Maandoverzicht",
    wsTab_clients: "Clients",
    wsTab_editors: "Editors",
    wsShoot_wrapped: "Wrapped",
    wsShoot_tentative: "Tentative",
    wsShoot_waiting: "Waiting on Client",
    wsShoot_planned: "Planned",
    wsStage_development: "Development",
    wsStage_preproduction: "Pre-Production",
    wsStage_shooting: "Shooting",
    wsStage_postproduction: "Post-Production",
    wsStage_completed: "Completed",
    wsRes_scripts: "Scripts & Docs",
    wsRes_props: "Props",
    wsRes_cast: "Cast",
    wsRes_shotlist: "Shotlist",
    wsRes_moodboard: "Moodboard & Refs",
    wsRes_interview: "Interview vragen",
    wsRatio_reels: "9:16 Reels",
    wsRatio_youtube: "16:9 YouTube",
    wsRatio_feed: "1:1 Feed",
    wsRatio_portrait: "4:5 Portrait",
    wsStyle_fastcuts: "Snelle cuts",
    wsStyle_cinematic: "Rustig & cinematisch",
    wsStyle_textoverlays: "Tekst overlays",
    wsStyle_voiceover: "Voice-over",
    wsStyle_musicheavy: "Muziek zwaar",
    wsStyle_mooddriven: "Sfeer-gedreven",
    shotlistAdd: "+ Shot",
    reset: "↺ Reset alle vinkjes",
    shootMode: "⛶ Shoot-modus",
    exitShootMode: "✕ Shoot-modus",
    script: "Script",
    brandAssets: "Brand Assets",
    shotlist: "Shotlist",
    sop: "SOP",
    stuurNaarKlant: "→ Stuur naar klant",
    bijKlant: "👁 Bij klant",
    klantAkkoord: "✓ Klant akkoord",

    loginWrongRoleTeam:
      "Dit account is geen teamaccount. Gebruik een teamaccount in Team-modus.",
    loginWrongRoleClient:
      "Dit account is geen klantaccount. Gebruik een klantaccount in Klant-modus.",
    loginInvalid: "Ongeldig e-mailadres of wachtwoord.",
    loginSuccess: "Succesvol ingelogd. Je wordt doorgestuurd…",
    loginNetworkError:
      "Geen verbinding met de server. Controleer je internet of probeer later opnieuw.",
    loginValEmailRequired: "Vul je e-mailadres in.",
    loginValEmailInvalid: "Vul een geldig e-mailadres in.",
    loginValPasswordRequired: "Vul je wachtwoord in.",
    loginValPasswordSpaces: "Wachtwoord mag niet alleen spaties zijn.",
    loginValServerForm:
      "E-mail en wachtwoord zijn verplicht en het e-mailadres moet geldig zijn.",
    forgotPasswordLink: "Wachtwoord vergeten?",
    forgotTitle: "Wachtwoord herstellen",
    forgotSub:
      "Vul het e-mailadres van je klantportaal in. Als dit adres bij een account hoort, sturen we je een link om je wachtwoord te herstellen.",
    forgotSubmit: "Link versturen",
    forgotSubmitLoading: "Bezig…",
    forgotBack: "← Terug naar inloggen",
    forgotSuccess:
      "Als dit e-mailadres bij een portaalaccount hoort, ontvang je een herstelmail. Controleer ook je spam.",
    resetCheckingLink: "Link controleren…",
    resetTitle: "Nieuw wachtwoord",
    resetSub: "Kies een nieuw wachtwoord voor je klantportaal.",
    resetNewPasswordLabel: "Nieuw wachtwoord",
    resetConfirmPasswordLabel: "Bevestig wachtwoord",
    resetSubmit: "Wachtwoord opslaan",
    resetSubmitLoading: "Opslaan…",
    resetBackToLogin: "← Terug naar inloggen",
    resetSuccess: "Je wachtwoord is bijgewerkt. Je kunt nu inloggen.",
    resetInvalidTitle: "Ongeldige link",
    resetInvalidLink:
      "Deze herstellink is ongeldig of verlopen. Vraag een nieuwe link aan.",
    resetValPasswordMismatch: "Wachtwoorden komen niet overeen.",
    resetValConfirmRequired: "Bevestig je wachtwoord.",
    portalTitleClient: "Klantportaal",
    portalTitleTeam: "4REEL Team",
    portalSubClient: "Log in met je accountgegevens",
    portalSubTeam: "Log in met je teamaccount",
    portalTabClient: "👤 Klant",
    portalTabTeam: "🔐 4REEL Team",
    portalEmailLabel: "Emailadres",
    portalPasswordLabel: "Wachtwoord",
    portalEmailPlaceholder: "jouw@email.nl",
    portalLoginSubmit: "Inloggen →",
    portalLoginSubmitLoading: "Inloggen…",
    portalPoweredBy: "Beveiligd portaal · 4REEL Productions",
    portalLoginTypeAria: "Inlogtype",
    portalTeamLoggedTitle: "Ingelogd als teamlid",
    portalTeamLoggedBody: "Gebruik het dashboard voor teamtoegang.",
    portalTeamLoggedLink: "→ Ga naar dashboard",
    eventCreateForbidden: "Alleen team mag events aanmaken.",
    eventValidationNameRequired: "Vul een eventnaam in.",
    eventValidationDateRequired: "Kies een datum.",
    eventValidationDateTimeRequired: "Kies datum en tijd.",
    eventValidationAssigneeRequired: "Wijs het event toe aan een teamlid.",
    eventValidationClientRequired: "Selecteer een klant.",
    eventSaveFailed: "Event kon niet worden opgeslagen.",
    addTeamMember: "Teamlid toevoegen",
    addTeamMemberTitle: "Nieuw teamlid",
    teamEmailLabel: "E-mail",
    teamPasswordLabel: "Wachtwoord",
    teamNameLabel: "Naam",
    teamRoleLabel: "Rol",
    teamInitialsLabel: "Initialen",
    teamColorLabel: "Kleur",
    teamLoadError: "Team kon niet worden geladen.",
    teamCreateError: "Teamlid kon niet worden aangemaakt.",
    teamEditTooltip: "Teamlid bewerken",
    teamDeleteTooltip: "Teamlid verwijderen",
    editTeamMemberTitle: "Teamlid bewerken",
    teamPasswordOptionalHint: "Leeg laten om ongewijzigd te laten",
    teamDeleteConfirmTitle: "Teamlid verwijderen?",
    teamDeleteConfirmBody:
      "Weet je zeker dat je {name} wilt verwijderen? Dit is een permanente verwijdering.",
    teamPasswordHint: "Minimaal 8 tekens",
    teamLoading: "Laden…",
    teamValEmailRequired: "E-mail is verplicht.",
    teamValEmailInvalid: "Vul een geldig e-mailadres in.",
    teamValEmailTaken: "Dit e-mailadres is al in gebruik.",
    teamValPasswordRequired: "Wachtwoord is verplicht.",
    teamValPasswordLength: "Wachtwoord moet minimaal 8 tekens zijn.",
    teamValNameRequired: "Naam is verplicht.",
    teamValRoleRequired: "Rol is verplicht.",
    taskFormTitle: "Nieuwe taak aanmaken",
    taskTitleLabel: "Titel",
    taskTitlePlaceholder: "Taaknaam…",
    taskAssigneeLabel: "Toegewezen aan",
    taskAssigneePlaceholder: "— Kies teamlid —",
    taskAssigneeEmpty: "Geen teamleden",
    taskPriorityLabel: "Prioriteit",
    taskDeadlineLabel: "Deadline",
    taskClientLabel: "Klant",
    taskClientPlaceholder: "— Kies klant —",
    taskCreateSubmit: "Taak aanmaken",
    taskArchivedToast: "Taak gearchiveerd",
    taskDeleteConfirmTitle: "Verwijderen",
    taskDeleteConfirmBody: "Weet je zeker dat je de taak {name} wilt verwijderen?",
    taskDeleteConfirmHint:
      "Deze actie verwijdert de taak niet permanent, maar zet de status op delete.",
    taskPriorityHigh: "Hoog",
    taskPriorityNormal: "Normaal",
    taskPriorityLow: "Laag",
    taskValTitleRequired: "Vul een titel in.",
    taskValTitleMax: "Titel mag maximaal 200 tekens zijn.",
    taskValAssigneeRequired: "Toegewezen aan is verplicht.",
    taskValAssigneeNoTeam: "Er zijn geen teamleden om toe te wijzen.",
    taskValAssigneeInvalid: "Kies een geldig teamlid.",
    taskValPriorityInvalid: "Kies een geldige prioriteit.",
    taskValDueRequired: "Kies een deadline.",
    taskValDueInvalid: "Kies een geldige datum.",
    taskValClientRequired: "Selecteer een klant.",
    taskValClientInvalid: "Kies een geldige klant uit de lijst.",
    taskDescriptionLabel: "Beschrijving",
    taskDescriptionPlaceholder: "Voeg extra context toe voor dit taakitem…",
    taskDescriptionEmpty: "Nog geen beschrijving.",
    taskLinksLabel: "Links",
    taskLinksEmpty: "Nog geen links toegevoegd.",
    taskAddLink: "+ Link",
    taskLinkLabelPlaceholder: "Link label (optioneel)",
    taskLinkUrlPlaceholder: "https://...",
    taskLinkUrlInvalid: "Gebruik een geldige URL die begint met http:// of https://.",
    taskChecklistLabel: "Checklist",
    taskChecklistCreate: "+ Checklist",
    taskChecklistEmpty: "Nog geen checklist-items.",
    taskChecklistDefaultItem: "Nieuwe checklist item",
    taskChecklistItemPlaceholder: "Voeg checklist item toe…",
    taskChecklistAddItem: "Item toevoegen",
    taskCommentsLabel: "Comments en activity",
    taskCommentsEmpty: "Nog geen opmerkingen.",
    taskCommentPlaceholder: "Schrijf een opmerking…",
    taskCommentAdd: "Opmerking toevoegen",
    taskMoveToLabel: "Verplaats naar",

    archivePageTitle: "Archief",
    archivePageTitleEm: "— Afgeronde taken",
    archiveArchivedTasksSuffix: "gearchiveerde taken",
    archiveAllTasks: "Alle taken",
    archiveSearchPlaceholder: "Zoeken…",
    archiveMonth: "Maand",
    archiveAllMonths: "Alle maanden",
    archivePerson: "Persoon",
    archiveEveryone: "Iedereen",
    archiveFilterReason: "Status",
    archiveAll: "Alles",
    archiveReasonDelivered: "Opgeleverd",
    archiveReasonCompleted: "Afgerond",
    archiveReasonManual: "Handmatig",
    archiveSort: "Sorteren",
    archiveSortNewest: "Nieuwste eerst",
    archiveSortOldest: "Oudste eerst",
    archiveSortAZ: "A → Z",
    archiveSortZA: "Z → A",
    archiveReset: "↺ Reset",
    archiveClientFallback: "Client",
    archiveActiveFilterSingular: "1 actieve filter",
    archiveActiveFilterPlural: "{n} actieve filters",
    archiveOf: "van",
    archiveTaskWord: "taken",
    archiveEmpty: "Geen taken gevonden met de huidige filters.",
    archiveClearFilters: "↺ Filters wissen",
    archiveModalAssignee: "Toegewezen",
    archiveModalArchived: "Gearchiveerd",
    archiveModalReason: "Reden",
    archiveModalDescription: "Beschrijving",
    archiveModalChecklist: "Checklist",
    archiveRestoreToTodo: "↩ Herstellen naar To Do",
    taskRestoredToast: "Taak hersteld",

    pulseTeamOnly: "Studio Pulse is alleen beschikbaar voor het team.",
    pulseLoadError: "Kon Studio Pulse niet laden.",
    pulsePageTitle: "Studio Pulse",
    pulsePageTitleEm: "— Bedrijfsgezondheid",
    pulseSubtitle: "Live inzicht in workload, pipeline en groei",
    pulseRefresh: "Vernieuwen",
    pulseKpiBatchesActive: "Batches actief",
    pulseKpiClientsSubOne: "{n} klant",
    pulseKpiClientsSubMany: "{n} klanten",
    pulseKpiVideosPipeline: "Videos in pipeline",
    pulseKpiNotStartedSub: "{n} nog te starten",
    pulseKpiShootsPlanned: "Shoots gepland",
    pulseKpiThisMonthSub: "{n} deze maand",
    pulseKpiDeliveredEver: "Opgeleverd ooit",
    pulseKpiDeliveredSubMonth: "{delivered} deze maand",
    pulseKpiDeliveredSubTasksSuffix: " · {openTasks} open taken",
    pulseStageNotStarted: "Nog te starten",
    pulseStageInEdit: "In bewerking",
    pulseStageInReview: "In review",
    pulseStageDelivered: "Opgeleverd",
    pulseCardPipeline: "Video Pipeline",
    pulseTeamCapacity: "Team Capaciteit",
    pulseTeamEmpty:
      "Nog geen teamleden of editors gekoppeld. Voeg teamleden toe of wijs een editor toe bij een batch.",
    pulseTeamLoadTooltip: "Videos in actieve fases",
    pulseCapacityAlmostFull: "Bijna vol",
    pulseCapacityGood: "Goed bezet",
    pulseCapacityRoom: "Ruimte beschikbaar",
    pulseCapacityHealthy: "Gezond",
    pulseCardReminders: "🔔 Slimme reminders",
    pulseAlertDeadlineToday: "Deadline VANDAAG: {name}",
    pulseAlertDeadlineOneDay: "Deadline over 1 dag: {name}",
    pulseAlertDeadlineDays: "Deadline over {days} dagen: {name}",
    pulseAlertDeadlineVideosOne: "{open} video nog niet klaar voor {client}",
    pulseAlertDeadlineVideosMany: "{open} videos nog niet klaar voor {client}",
    pulseThisClient: "deze klant",
    pulseAlertDeadlineAction: "Ga naar Workspace → {target}",
    pulseAlertLowWorkloadTitle: "Lage workload — ruimte voor nieuwe klanten",
    pulseAlertLowWorkloadDesc:
      "Team zit op {pct}% capaciteit. Goed moment voor acquisitie.",
    pulseAlertLowWorkloadAction: "Overweeg {n} nieuwe projecten aan te nemen",
    pulseAlertHighWorkloadTitle: "Team bijna vol — {pct}% bezet",
    pulseAlertHighWorkloadDesc:
      "Wees voorzichtig met het aannemen van nieuwe opdrachten.",
    pulseAlertHighWorkloadAction: "Bespreek capaciteitsplanning met het team",
    pulseAlertReviewTitle: "{n} videos wachten op review/feedback",
    pulseAlertReviewDesc: "Follow-up bij klanten versnelt de pipeline.",
    pulseAlertReviewAction: "Controleer: Workspace → Export links verzonden?",
    pulseAlertShootsLowTitle: "Weinig shoots ingepland ({n})",
    pulseAlertShootsLowDesc:
      "Minder dan 2 shoots gepland voor de komende periode.",
    pulseAlertShootsLowAction: "Plan nieuwe shootdagen in via de Agenda",
    pulseAlertIdleClientsOne: "1 klant zonder actieve videos",
    pulseAlertIdleClientsMany: "{n} klanten zonder actieve videos",
    pulseAlertIdleClientsAction: "Stuur een check-in of plan nieuwe shoot in",
    pulseAlertAllGoodTitle: "Alles ziet er goed uit!",
    pulseAlertAllGoodDesc: "Geen urgente aandachtspunten gevonden. Goed bezig!",
    pulseCardGrowth: "📈 Groei — opgeleverde projecten",
    pulseGrowthEmpty: "Nog geen maandoverzicht beschikbaar.",
    pulseGrowthFootnote:
      "Laatste 6 maanden · gearchiveerde taken + opgeleverde workspace videos",
    pulseCardClientHealth: "🏢 Klantgezondheid",
    pulseClientsEmpty: "Nog geen klanten — voeg klanten toe onder Klanten.",
    pulseClientBatchOne: "batch",
    pulseClientBatchMany: "batches",
    pulseClientVideoOne: "video",
    pulseClientVideoMany: "videos",
    pulseClientUrgent: "Urgent",
    pulseBannerTitle: "Capaciteitsruimte beschikbaar",
    pulseBannerBody:
      "Het team kan nog ca. {n} nieuwe projecten aan. Nu is het moment voor acquisitie.",
    pulseBannerCta: "→ Naar klanten",
  },
  en: {
    brandSub: "Video Production Studio",
    navStudio: "Studio",
    navBeheer: "Operations",
    navEditors: "Editors",
    team: "Team",
    logout: "Log out",
    logoutConfirmTitle: "Log out?",
    logoutConfirmBody: "Are you sure you want to log out?",
    home: "Home",
    agenda: "Agenda",
    klanten: "Clients",
    taken: "Tasks",
    archief: "Archive",
    workspace: "Workspace",
    checker: "Video Checker",
    pulse: "Studio Pulse",
    activeClients: "Active clients",
    openTasks: "Open tasks",
    shootsMonth: "Shoots this month",
    urgent: "Urgent",
    kpiTasksInProgress: "Tasks in progress",
    kpiUrgentClients: "Urgent clients",
    kpiDescOngoingProjects: "Ongoing projects",
    kpiDescScheduled: "Scheduled",
    kpiDescAcrossProjects: "Across all projects",
    kpiDescRequiresAttention: "Requires attention",
    dayModalNoEvents: "No events on this day.",
    addEventToDay: "+ Add event",
    eventFormTitle: "Add new event",
    eventFormTitleEdit: "Edit event",
    eventDateTimeLabel: "Date and time",
    eventAssigneeLabel: "Assigned to",
    eventAssigneePlaceholder: "— Select team member —",
    eventNameLabel: "Name",
    eventNamePlaceholder: "Event name…",
    eventDateLabel: "Date",
    eventClientLabel: "Client",
    eventClientPlaceholder: "— Select client —",
    eventNotesPlaceholder: "Optional…",
    thisWeek: "This week",
    nextWeek: "Next week",
    homeStudioSubtitle: "Studio overview · 4REEL Productions",
    activity: "Activity",
    clientActivityOverview: "Client activity overview",
    clientActivityEmpty: "No client activity yet",
    clientActivityLoadError: "Could not load client activity",
    portalUnknownClient: "Unknown client",
    portalClientEventFallback: "New portal activity",
    portalDateUnknown: "Unknown date",
    contact: "Contact person",
    phone: "Phone",
    clientSince: "Client since",
    phase: "Phase",
    statusLabel: "Status",
    urgentStatus: "Urgent",
    active: "Active",
    notes: "Notes",
    todo: "To do",
    bezig: "In progress",
    review: "Review",
    klaar: "Done",
    filter: "Filter:",
    allTasks: "All",
    tasksKanbanSubtitle: "Project tasks across all clients",
    addTask: "+ Task",
    addEvent: "+ New event",
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    delete: "Delete",
    restore: "↩ Restore",
    archive: "→ Archive",
    wsFilmsLabel: "Videos",
    wsFilmsReady: "ready",
    wsVidColName: "Filename",
    wsVidColFase: "Edit Phase",
    wsVidColAssets: "Assets Drive",
    wsVidColExport: "Export Frame.io",
    wsVidColNotes: "Notes",
    wsAddDrivePH: "+ Add Drive link",
    wsAddExportPH: "+ Frame.io link",
    wsVidNamePrompt: "Video filename:",
    wsAddWorkspace: "+ Add Workspace",
    wsAddNewBatch: "+ Add new batch",
    wsAddWorkspaceFooter: "+ Create workspace",
    wsAddVideo: "+ Video",
    wsBackAllBatches: "← All workspaces",
    wsDeleteWorkspace: "Delete workspace",
    wsEditProject: "Edit project",
    wsConfirmDeleteBatch: "Delete \"{name}\"?",
    wsBackAllWorkspaces: "← All workspaces",
    wsBatchesLabel: "Batches",
    wsBatchesEmpty: "No batches yet. Create one to add videos.",
    wsNewBatchTitle: "New batch",
    wsBatchNameLabel: "Batch name",
    wsBatchNameExample: "e.g. Shoot week 1",
    wsCreateBatch: "Create batch",
    wsDeleteBatchBtn: "Delete batch",
    wsConfirmDeleteBatchSub: "Delete batch \"{name}\" and all its videos?",
    wsSelectBatchFirst: "Select a batch first.",
    wsVideosInBatchNamed: "Videos in {name} ({total})",
    wsShootLabel: "Shoot",
    wsShootStatusLabel: "Shoot status",
    wsShootDateLabel: "Shoot date",
    wsShootTimeLabel: "Shoot time",
    wsShootTimeRequiredError: "Shoot time is required.",
    wsDeadlineLabel: "Deadline",
    wsEditorLabel: "Editor",
    wsLeadEditorLabel: "Lead editor",
    wsTeamPlaceholder: "— Select team —",
    wsProjectStageLabel: "Project stage",
    wsBatchNotes: "Batch notes",
    wsProjectLinksTitle: "🔗 Project links (Drive · LUTs · B-Roll · Premiere)",
    wsOpenLink: "Open ↗",
    wsLinkLabelPlaceholder: "Label (e.g. LUTs folder)",
    wsLinkUrlPlaceholder: "https://drive.google.com/...",
    wsAddLink: "+ Add link",
    wsWorkflowTitle: "📋 Workflow — how do we handle these files?",
    wsWorkflowStep1Title: "Download assets",
    wsWorkflowStep1Desc:
      "Download the footage from the Drive link above. Store each batch in a separate folder on your local drive. Do NOT rename files.",
    wsWorkflowStep2Title: "Create project in Premiere",
    wsWorkflowStep2Desc:
      "Use the Premiere Pro template from the link above. Load the LUTs folder for the correct color profile per project.",
    wsWorkflowStep3Title: "Start editing → set status to \"In Progress\"",
    wsWorkflowStep3Desc:
      "Edit the video based on the shotlist and interview questions. Set the Edit Phase to In Progress as soon as you start.",
    wsWorkflowStep4Title: "Export with exact filename",
    wsWorkflowStep4Desc:
      "Export using the exact name shown in the table below, including version number.",
    wsWorkflowStep5Title: "Upload to Frame.io → paste link in Export column",
    wsWorkflowStep5Desc:
      "Upload the exported video to Frame.io and paste the link in Export Frame.io.",
    wsWorkflowStep6Title: "Edit phase → \"Waiting for Review\"",
    wsWorkflowStep6Desc:
      "Set Edit Phase to Waiting for Review. After approval → Finished.",
    wsVideosInBatch: "Videos in batch ({total})",
    wsVideosDoneProgress: "{done}/{total} done",
    wsFilenamePlaceholder: "Filename…",
    wsEditScript: "Edit script",
    wsScriptAdd: "Add script…",
    wsDriveLinkPlaceholder: "Drive link…",
    wsOpenShotlist: "Open shotlist",
    wsCreateShotlist: "Create shotlist…",
    wsEditSop: "Edit SOP",
    wsFillSop: "Fill SOP…",
    wsNotePlaceholder: "Note…",
    wsInternApprovedSend: "Internally approved — send to client",
    wsApproveInternFirst: "Approve internally first",
    wsToPortal: "→ Portal",
    wsDeleteVideoAria: "Delete video",
    wsConfirmDeleteVideo: "Delete video?",
    wsOptionalNote: "Note (optional)",
    wsAddItem: "+ Add",
    wsNewVideoTitle: "New video",
    wsVideoNameExample: "e.g. Kalea_Intro_Reel_v1",
    wsPageSubtitle: "Project batches video statuses resources",
    wsShootDateHeader: "Shoot date",
    wsShootStatusHeader: "Shoot status",
    wsBatchProjectHeader: "Batch / Project",
    wsVideosHeader: "Videos",
    wsDeadlineHeader: "Deadline",
    wsStageHeader: "Stage",
    wsEditorHeader: "Editor",
    wsClientHeader: "Client",
    wsFilmSingular: "film",
    wsFilmPlural: "films",
    wsNewWorkspaceProject: "New workspace project",
    wsProjectNameLabel: "Project name",
    wsProjectNameExample: "e.g. Vermado Automotive S2",
    wsProjectNameRequired: "Project name is required.",
    wsEditorRoleEditor: "Editor",
    wsCreateProject: "Create project",
    wsScriptPlaceholder:
      "Paste or type the script, brief, or notes for this video here.\n\nTip: copy directly from Google Docs or Notion.",
    wsScriptStats: "{words} words · {chars} characters",
    wsCloseShootMode: "✕ Close shoot mode",
    wsShotsDone: "shots captured",
    wsNoShots: "No shots yet. Add one below.",
    wsShotAddPlaceholder: "Add shot, e.g: Wide entrance shot · Product close-up…",
    wsScriptUnavailable:
      "No script available for this video.\n\nAdd a script through the Script column in the table.",
    wsSopFormatRatio: "🎞 Format & Ratio",
    wsSopDurationLabel: "Duration (e.g. 60s, 3 min YouTube)",
    wsSopDurationPlaceholder: "e.g. 60s reels + 3 min YouTube",
    wsSopStyleFeel: "🎨 Style & Feel",
    wsSopLutLabel: "Color profile / LUT",
    wsSopLutPlaceholder: "e.g. Warm, high contrast — LUT: Moody_v3",
    wsSopMusicAudio: "🎵 Music & Audio",
    wsSopMusicPlaceholder:
      "e.g. Energetic, upbeat. No lyrics. Artlist — search: urban cinematic",
    wsSopEditorInstructions: "📋 Instructions for editor",
    wsSopInstructionsPlaceholder:
      "Example:\n• Start with the strongest shot\n• Use jump cuts for energy\n• Subtitles required on reels\n• Export H.264, max 100MB\n• Color: warm and sunny",
    wsSopTip:
      "💡 Fill this in for the editing phase so the editor clearly understands the goal and there are fewer revisions.",
    wsSopAutoSaved: "Auto-saved · Click outside the modal to close",
    wsFase_tentative: "Tentative",
    wsFase_spotting: "Spotting Footage",
    wsFase_inprogress: "In Progress",
    wsFase_ready: "Ready to Edit",
    wsFase_intern_review: "Internal Review",
    wsFase_intern_approved: "Internally Approved ✓",
    wsFase_waitreview: "Send to client →",
    wsFase_client_review: "In client review",
    wsFase_client_revision: "Revision requested",
    wsFase_client_approved: "Approved by client ✓",
    wsFase_uploaddrive: "Upload to Drive",
    wsFase_finished: "Finished ✓",
    wsGroup_intern: "── Internal ──",
    wsGroup_client: "── Client ──",
    wsGroup_done: "── Finish ──",
    wsTab_inbox: "Project Inbox",
    wsTab_stage: "Project Stage",
    wsTab_deadlines: "Posting Deadlines",
    wsTab_shoots: "Scheduled Shoots",
    wsTab_month: "Month View",
    wsTab_clients: "Clients",
    wsTab_editors: "Editors",
    wsShoot_wrapped: "Wrapped",
    wsShoot_tentative: "Tentative",
    wsShoot_waiting: "Waiting on Client",
    wsShoot_planned: "Planned",
    wsStage_development: "Development",
    wsStage_preproduction: "Pre-Production",
    wsStage_shooting: "Shooting",
    wsStage_postproduction: "Post-Production",
    wsStage_completed: "Completed",
    wsRes_scripts: "Scripts & Docs",
    wsRes_props: "Props",
    wsRes_cast: "Cast",
    wsRes_shotlist: "Shotlist",
    wsRes_moodboard: "Moodboard & Refs",
    wsRes_interview: "Interview questions",
    wsRatio_reels: "9:16 Reels",
    wsRatio_youtube: "16:9 YouTube",
    wsRatio_feed: "1:1 Feed",
    wsRatio_portrait: "4:5 Portrait",
    wsStyle_fastcuts: "Fast cuts",
    wsStyle_cinematic: "Calm & cinematic",
    wsStyle_textoverlays: "Text overlays",
    wsStyle_voiceover: "Voice-over",
    wsStyle_musicheavy: "Music-heavy",
    wsStyle_mooddriven: "Mood-driven",
    shotlistAdd: "+ Shot",
    reset: "↺ Reset all checks",
    shootMode: "⛶ Shoot mode",
    exitShootMode: "✕ Shoot mode",
    script: "Script",
    brandAssets: "Brand Assets",
    shotlist: "Shotlist",
    sop: "SOP",
    stuurNaarKlant: "→ Send to client",
    bijKlant: "👁 At client",
    klantAkkoord: "✓ Client approved",

    loginWrongRoleTeam:
      "This account is not a team account. Use a team account in Team mode.",
    loginWrongRoleClient:
      "This account is not a client account. Use a client account in Client mode.",
    loginInvalid: "Invalid email or password.",
    loginSuccess: "Signed in successfully. Redirecting…",
    loginNetworkError:
      "Could not reach the server. Check your connection or try again later.",
    loginValEmailRequired: "Enter your email address.",
    loginValEmailInvalid: "Enter a valid email address.",
    loginValPasswordRequired: "Enter your password.",
    loginValPasswordSpaces: "Password cannot be only spaces.",
    loginValServerForm:
      "Email and password are required and the email must be valid.",
    forgotPasswordLink: "Forgot password?",
    forgotTitle: "Reset password",
    forgotSub:
      "Enter the email address you use for the client portal. If it matches an account, we will send a link to reset your password.",
    forgotSubmit: "Send reset link",
    forgotSubmitLoading: "Please wait…",
    forgotBack: "← Back to sign in",
    forgotSuccess:
      "If this email is linked to a portal account, you will receive a reset email. Check your spam folder too.",
    resetCheckingLink: "Checking your link…",
    resetTitle: "New password",
    resetSub: "Choose a new password for your client portal.",
    resetNewPasswordLabel: "New password",
    resetConfirmPasswordLabel: "Confirm password",
    resetSubmit: "Save password",
    resetSubmitLoading: "Saving…",
    resetBackToLogin: "← Back to sign in",
    resetSuccess: "Your password has been updated. You can sign in now.",
    resetInvalidTitle: "Invalid link",
    resetInvalidLink:
      "This reset link is invalid or has expired. Request a new one.",
    resetValPasswordMismatch: "Passwords do not match.",
    resetValConfirmRequired: "Please confirm your password.",
    portalTitleClient: "Client portal",
    portalTitleTeam: "4REEL Team",
    portalSubClient: "Sign in with your account details",
    portalSubTeam: "Sign in with your team account",
    portalTabClient: "👤 Client",
    portalTabTeam: "🔐 4REEL Team",
    portalEmailLabel: "Email",
    portalPasswordLabel: "Password",
    portalEmailPlaceholder: "you@email.com",
    portalLoginSubmit: "Sign in →",
    portalLoginSubmitLoading: "Signing in…",
    portalPoweredBy: "Secure portal · 4REEL Productions",
    portalLoginTypeAria: "Sign-in type",
    portalTeamLoggedTitle: "Signed in as team member",
    portalTeamLoggedBody: "Use the dashboard for team access.",
    portalTeamLoggedLink: "→ Go to dashboard",
    eventCreateForbidden: "Only team members can create events.",
    eventValidationNameRequired: "Enter an event name.",
    eventValidationDateRequired: "Choose a date.",
    eventValidationDateTimeRequired: "Choose date and time.",
    eventValidationAssigneeRequired: "Assign the event to a team member.",
    eventValidationClientRequired: "Select a client.",
    eventSaveFailed: "Could not save the event.",
    addTeamMember: "Add member",
    addTeamMemberTitle: "New team member",
    teamEmailLabel: "Email",
    teamPasswordLabel: "Password",
    teamNameLabel: "Name",
    teamRoleLabel: "Role",
    teamInitialsLabel: "Initials",
    teamColorLabel: "Color",
    teamLoadError: "Could not load the team.",
    teamCreateError: "Could not create the team member.",
    teamEditTooltip: "Edit team member",
    teamDeleteTooltip: "Delete team member",
    editTeamMemberTitle: "Edit team member",
    teamPasswordOptionalHint: "Leave empty to keep unchanged",
    teamDeleteConfirmTitle: "Delete team member?",
    teamDeleteConfirmBody:
      "Are you sure you want to delete {name}? This permanently removes the account.",
    teamPasswordHint: "At least 8 characters",
    teamLoading: "Loading…",
    teamValEmailRequired: "Email is required.",
    teamValEmailInvalid: "Enter a valid email address.",
    teamValEmailTaken: "That email address is already in use.",
    teamValPasswordRequired: "Password is required.",
    teamValPasswordLength: "Password must be at least 8 characters.",
    teamValNameRequired: "Name is required.",
    teamValRoleRequired: "Role is required.",
    taskFormTitle: "Create new task",
    taskTitleLabel: "Title",
    taskTitlePlaceholder: "Task name…",
    taskAssigneeLabel: "Assigned to",
    taskAssigneePlaceholder: "— Select team member —",
    taskAssigneeEmpty: "No team members",
    taskPriorityLabel: "Priority",
    taskDeadlineLabel: "Due date",
    taskClientLabel: "Client",
    taskClientPlaceholder: "— Select client —",
    taskCreateSubmit: "Create task",
    taskArchivedToast: "Task archived",
    taskDeleteConfirmTitle: "Delete",
    taskDeleteConfirmBody: "Are you sure you want to delete task {name}?",
    taskDeleteConfirmHint:
      "This action does not permanently remove the task, it sets the status to delete.",
    taskPriorityHigh: "High",
    taskPriorityNormal: "Normal",
    taskPriorityLow: "Low",
    taskValTitleRequired: "Enter a title.",
    taskValTitleMax: "Title must be at most 200 characters.",
    taskValAssigneeRequired: "Assigned to is required.",
    taskValAssigneeNoTeam: "There are no team members to assign.",
    taskValAssigneeInvalid: "Choose a valid team member.",
    taskValPriorityInvalid: "Choose a valid priority.",
    taskValDueRequired: "Choose a due date.",
    taskValDueInvalid: "Choose a valid date.",
    taskValClientRequired: "Select a client.",
    taskValClientInvalid: "Choose a valid client from the list.",
    taskDescriptionLabel: "Description",
    taskDescriptionPlaceholder: "Add more context for this task…",
    taskDescriptionEmpty: "No description yet.",
    taskLinksLabel: "Links",
    taskLinksEmpty: "No links added yet.",
    taskAddLink: "+ Link",
    taskLinkLabelPlaceholder: "Link label (optional)",
    taskLinkUrlPlaceholder: "https://...",
    taskLinkUrlInvalid: "Use a valid URL starting with http:// or https://.",
    taskChecklistLabel: "Checklist",
    taskChecklistCreate: "+ Checklist",
    taskChecklistEmpty: "No checklist items yet.",
    taskChecklistDefaultItem: "New checklist item",
    taskChecklistItemPlaceholder: "Add checklist item…",
    taskChecklistAddItem: "Add item",
    taskCommentsLabel: "Comments and activity",
    taskCommentsEmpty: "No comments yet.",
    taskCommentPlaceholder: "Write a comment…",
    taskCommentAdd: "Add comment",
    taskMoveToLabel: "Move to",

    archivePageTitle: "Archive",
    archivePageTitleEm: "— Completed tasks",
    archiveArchivedTasksSuffix: "archived tasks",
    archiveAllTasks: "All tasks",
    archiveSearchPlaceholder: "Search…",
    archiveMonth: "Month",
    archiveAllMonths: "All months",
    archivePerson: "Person",
    archiveEveryone: "Everyone",
    archiveFilterReason: "Reason",
    archiveAll: "All",
    archiveReasonDelivered: "Delivered",
    archiveReasonCompleted: "Completed",
    archiveReasonManual: "Manual",
    archiveSort: "Sort",
    archiveSortNewest: "Newest first",
    archiveSortOldest: "Oldest first",
    archiveSortAZ: "A → Z",
    archiveSortZA: "Z → A",
    archiveReset: "↺ Reset",
    archiveClientFallback: "Client",
    archiveActiveFilterSingular: "1 active filter",
    archiveActiveFilterPlural: "{n} active filters",
    archiveOf: "of",
    archiveTaskWord: "tasks",
    archiveEmpty: "No tasks match the current filters.",
    archiveClearFilters: "↺ Clear filters",
    archiveModalAssignee: "Assigned",
    archiveModalArchived: "Archived",
    archiveModalReason: "Reason",
    archiveModalDescription: "Description",
    archiveModalChecklist: "Checklist",
    archiveRestoreToTodo: "↩ Restore to To do",
    taskRestoredToast: "Task restored",

    pulseTeamOnly: "Studio Pulse is only available to the team.",
    pulseLoadError: "Could not load Studio Pulse.",
    pulsePageTitle: "Studio Pulse",
    pulsePageTitleEm: "— Business health",
    pulseSubtitle: "Live view of workload, pipeline and growth",
    pulseRefresh: "Refresh",
    pulseKpiBatchesActive: "Active batches",
    pulseKpiClientsSubOne: "{n} client",
    pulseKpiClientsSubMany: "{n} clients",
    pulseKpiVideosPipeline: "Videos in pipeline",
    pulseKpiNotStartedSub: "{n} not yet started",
    pulseKpiShootsPlanned: "Shoots scheduled",
    pulseKpiThisMonthSub: "{n} this month",
    pulseKpiDeliveredEver: "Delivered (all time)",
    pulseKpiDeliveredSubMonth: "{delivered} this month",
    pulseKpiDeliveredSubTasksSuffix: " · {openTasks} open tasks",
    pulseStageNotStarted: "Not started",
    pulseStageInEdit: "In edit",
    pulseStageInReview: "In review",
    pulseStageDelivered: "Delivered",
    pulseCardPipeline: "Video pipeline",
    pulseTeamCapacity: "Team capacity",
    pulseTeamEmpty:
      "No team members or editors linked yet. Add team members or assign an editor on a batch.",
    pulseTeamLoadTooltip: "Videos in active stages",
    pulseCapacityAlmostFull: "Almost full",
    pulseCapacityGood: "Well utilised",
    pulseCapacityRoom: "Capacity available",
    pulseCapacityHealthy: "Healthy",
    pulseCardReminders: "🔔 Smart reminders",
    pulseAlertDeadlineToday: "Deadline TODAY: {name}",
    pulseAlertDeadlineOneDay: "Deadline in 1 day: {name}",
    pulseAlertDeadlineDays: "Deadline in {days} days: {name}",
    pulseAlertDeadlineVideosOne: "{open} video not yet done for {client}",
    pulseAlertDeadlineVideosMany: "{open} videos not yet done for {client}",
    pulseThisClient: "this client",
    pulseAlertDeadlineAction: "Go to Workspace → {target}",
    pulseAlertLowWorkloadTitle: "Low workload — room for new clients",
    pulseAlertLowWorkloadDesc:
      "The team is at {pct}% capacity. A good moment for new business.",
    pulseAlertLowWorkloadAction: "Consider taking on {n} new projects",
    pulseAlertHighWorkloadTitle: "Team nearly at capacity — {pct}% utilised",
    pulseAlertHighWorkloadDesc: "Be careful about taking on new assignments.",
    pulseAlertHighWorkloadAction: "Discuss capacity planning with the team",
    pulseAlertReviewTitle: "{n} videos waiting for review/feedback",
    pulseAlertReviewDesc: "Following up with clients speeds up the pipeline.",
    pulseAlertReviewAction: "Check: Workspace → export links sent?",
    pulseAlertShootsLowTitle: "Few shoots scheduled ({n})",
    pulseAlertShootsLowDesc:
      "Fewer than 2 shoots planned for the coming period.",
    pulseAlertShootsLowAction: "Schedule new shoot days in the Agenda",
    pulseAlertIdleClientsOne: "1 client with no active videos",
    pulseAlertIdleClientsMany: "{n} clients with no active videos",
    pulseAlertIdleClientsAction: "Send a check-in or schedule a new shoot",
    pulseAlertAllGoodTitle: "Everything looks good!",
    pulseAlertAllGoodDesc: "No urgent attention items. Keep it up!",
    pulseCardGrowth: "📈 Growth — delivered projects",
    pulseGrowthEmpty: "No monthly overview available yet.",
    pulseGrowthFootnote:
      "Last 6 months · archived tasks + delivered workspace videos",
    pulseCardClientHealth: "🏢 Client health",
    pulseClientsEmpty: "No clients yet — add clients under Clients.",
    pulseClientBatchOne: "batch",
    pulseClientBatchMany: "batches",
    pulseClientVideoOne: "video",
    pulseClientVideoMany: "videos",
    pulseClientUrgent: "Urgent",
    pulseBannerTitle: "Capacity available",
    pulseBannerBody:
      "The team can still take on about {n} new projects. A good moment for new business.",
    pulseBannerCta: "→ Go to clients",
  },
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState("nl");
  const t = (key, vars) => {
    let s = strings[lang][key];
    if (s == null) return key;
    if (vars && typeof vars === "object") {
      for (const [k, v] of Object.entries(vars)) {
        s = s.split(`{${k}}`).join(String(v));
      }
    }
    return s;
  };
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
